# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-19 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_dict',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
