# Generated by Django 2.1.5 on 2019-02-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_t_dict_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_dict',
            name='sub_category',
            field=models.CharField(default='', max_length=40),
        ),
    ]
