# Generated by Django 3.2.22 on 2023-10-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_t_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_dict',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='t_sub',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
