# Generated by Django 3.2.22 on 2023-10-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20231012_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rootid', models.IntegerField()),
                ('pledgeid', models.IntegerField(default='0')),
                ('currency', models.CharField(default='Bond', max_length=20)),
                ('amount', models.CharField(max_length=10)),
                ('purpose', models.CharField(max_length=30)),
                ('commitment', models.CharField(default='Cash', max_length=20)),
                ('ref', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('user', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
