# Generated by Django 3.2.22 on 2023-10-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_t_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_from', models.IntegerField(default='0')),
                ('payment_to', models.IntegerField(default='0')),
                ('purpose', models.CharField(max_length=10)),
                ('unit', models.IntegerField(default='0')),
                ('unit_cost', models.IntegerField(default='0')),
                ('total_cost', models.IntegerField(default='0')),
                ('notes', models.CharField(max_length=200)),
                ('user', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
