# Generated by Django 3.2.22 on 2023-10-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_t_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_expense',
            name='payment_from',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='t_expense',
            name='payment_to',
            field=models.CharField(max_length=50),
        ),
    ]
