# Generated by Django 2.1.5 on 2019-02-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_assets',
            name='department',
            field=models.CharField(default='office', max_length=120),
        ),
        migrations.AddField(
            model_name='t_assets',
            name='responsible',
            field=models.CharField(default='', max_length=120),
        ),
    ]
