# Generated by Django 2.1.5 on 2019-02-03 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0010_auto_20190128_1006'),
        ('assets', '0002_auto_20190203_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_assets',
            name='responsible',
        ),
        migrations.AddField(
            model_name='t_assets',
            name='rootid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='joins.t_acct'),
            preserve_default=False,
        ),
    ]
