# Generated by Django 2.1.5 on 2019-02-04 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20190203_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_assets',
            name='rootid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='joins.t_acct'),
        ),
    ]
