# Generated by Django 2.1.5 on 2019-02-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20190204_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_assets',
            name='equip_type',
            field=models.CharField(default='', max_length=120),
        ),
    ]
