# Generated by Django 2.1.5 on 2019-01-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0002_auto_20190125_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='zone',
            field=models.CharField(default='IOC', max_length=120),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(default='media', max_length=120),
        ),
    ]
