# Generated by Django 2.1.5 on 2019-01-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0004_auto_20190126_0204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_acct',
            old_name='site',
            new_name='zone',
        ),
        migrations.RemoveField(
            model_name='t_user_attribute',
            name='baptised',
        ),
        migrations.RemoveField(
            model_name='t_user_attribute',
            name='spiritual_maturity',
        ),
        migrations.RemoveField(
            model_name='t_user_attribute',
            name='years_in_ministry',
        ),
        migrations.RemoveField(
            model_name='t_user_attribute',
            name='zone',
        ),
        migrations.AddField(
            model_name='t_acct',
            name='baptised',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=10),
        ),
        migrations.AddField(
            model_name='t_acct',
            name='spiritual_maturity',
            field=models.CharField(default='ordinary', max_length=20),
        ),
        migrations.AddField(
            model_name='t_acct',
            name='years_in_ministry',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
    ]
