# Generated by Django 2.1.5 on 2019-01-26 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0005_auto_20190126_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_acct',
            name='division',
        ),
    ]
