# Generated by Django 2.1.5 on 2019-01-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0009_auto_20190128_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_acct',
            name='baptised',
            field=models.CharField(default='Yes', max_length=30),
        ),
        migrations.AlterField(
            model_name='t_acct',
            name='years_in_ministry',
            field=models.IntegerField(default='1'),
        ),
    ]
