# Generated by Django 3.1.1 on 2023-01-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0010_auto_20190128_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_acct',
            name='dob',
            field=models.DateField(blank=True, default='2022-01-01', null=True),
        ),
    ]
