# Generated by Django 3.2.22 on 2023-10-13 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0011_auto_20231012_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_acct_attributes',
            name='image',
        ),
        migrations.RemoveField(
            model_name='t_acct_attributes',
            name='years_in_ministry',
        ),
    ]
