# Generated by Django 3.2.22 on 2023-10-13 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0013_remove_t_acct_years_in_ministry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_acct_attributes',
            name='department',
        ),
        migrations.RemoveField(
            model_name='t_acct_attributes',
            name='zone',
        ),
    ]
