# Generated by Django 3.2.22 on 2023-10-17 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('joins', '0014_auto_20231013_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_acct',
            name='department',
        ),
        migrations.RemoveField(
            model_name='t_acct',
            name='email',
        ),
        migrations.RemoveField(
            model_name='t_acct',
            name='image',
        ),
        migrations.RemoveField(
            model_name='t_acct',
            name='user',
        ),
        migrations.RemoveField(
            model_name='t_acct',
            name='zone',
        ),
        migrations.AddField(
            model_name='t_acct',
            name='root',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_acct',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='t_acct',
            name='fname',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='t_acct',
            name='lname',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='t_acct_attributes',
        ),
    ]
