# Generated by Django 3.2.22 on 2023-10-17 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0015_auto_20231017_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_acct',
            old_name='user_id',
            new_name='user',
        ),
    ]
