# Generated by Django 2.1.5 on 2019-01-31 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0010_auto_20190128_1006'),
        ('libs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(default='IOC', max_length=120)),
                ('service', models.CharField(default='', max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('rootid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joins.t_acct')),
            ],
        ),
    ]
