# Generated by Django 2.1.5 on 2019-01-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0002_t_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_attendance',
            name='user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
