# Generated by Django 2.1.5 on 2019-02-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0003_t_attendance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_payment',
            name='amount',
            field=models.CharField(max_length=10),
        ),
    ]
