# Generated by Django 3.1.1 on 2023-01-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0004_auto_20190215_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_song',
            name='Artist',
            field=models.CharField(default='', max_length=50),
        ),
    ]
