# Generated by Django 3.2.22 on 2023-10-23 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0005_auto_20231012_2246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='t_payment',
        ),
    ]
