# Generated by Django 2.0.1 on 2019-01-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20190112_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
