# Generated by Django 2.0.1 on 2019-01-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=10)),
                ('image', models.ImageField(blank=True, default='', upload_to='images')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
