# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-03 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rootid', models.IntegerField()),
                ('price', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('status', models.CharField(default='status', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='t_product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='t_product',
            name='qty',
        ),
    ]
