# Generated by Django 2.0.1 on 2019-01-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190112_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rootid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
