# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-30 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteInfo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='t_contact',
        ),
        migrations.AlterField(
            model_name='t_dict',
            name='category',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='t_dict',
            name='link',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='t_dict',
            name='name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='t_urls',
            name='category',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='t_urls',
            name='icon',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='t_urls',
            name='link',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='t_urls',
            name='name',
            field=models.CharField(default='', max_length=120),
        ),
    ]
