# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-30 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteInfo', '0002_auto_20180130_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_urls',
            name='icon',
        ),
    ]
