# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-12 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteInfo', '0006_t_urls_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_urls',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
