# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-04 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteInfo', '0009_t_dictionary_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_dictionary',
            name='sub_category',
            field=models.CharField(default='', max_length=20),
        ),
    ]
